# Provide a custom message
config:
  message: "Welcome K8s"
  logo: kubernetes
# Remember to set service.type=ClusterIP if you are using an ingress
ingress:
  configured: false
  rewritePath: true
  pathPrefix: ""
service:
  type: NodePort
  port: 80
deployment:
  replicaCount: 2
  container:
    image:
      # repository: "swr.me-east-1.myhuaweicloud.com/yxy0325/nginx" 
      repository: "swr.cn-east-273.antacloud.com/test/nginx"
      tag: "zxw-test"
      pullPolicy: IfNotPresent
    port: 8080
  # Currently only linux images on amd64 architecture are supported - support for arm64 and windows/amd64 coming ...
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
  resources: {}
  tolerations: []
  affinity: {}
